### ISSUE TITLE
Request failed with 404

### ISSUE THREAD

**Issue by thanlok** [itering/subscan-essentials#72]
I was trying to start the services with docker but got these log in subscan-observer. The log keeps repeating. Any idea why?

```
subscan-observer_1  | sh: 1: ../target/subscan: not found
subscan-observer_1  | 2020/09/23 16:09:56 substrate not running
subscan-observer_1  | 2020/09/23 16:09:56 open /subscan/cmd/log/substrate_pid: no such file or directory
subscan-observer_1  | 2020/09/23 16:09:56 start watch filepath: ../configs
```

Here is my docker-compose yaml:

```
version: "2.4"
services:
  subscan-api:
    build: .
    image: subscan/api
    environment: &app_base
      MYSQL_HOST: mysql
      MYSQL_PASS: 'helloload'
      MYSQL_DB: 'subscan'
      REDIS_ADDR: redis:6379
      CHAIN_WS_ENDPOINT: 'ws://polkadot-test:9944'
      NETWORK_NODE: 'westend'
      WEB_HOST: 'http://subscan-api:4399'
    ports:
      - '4399:4399'
    networks:
      - app_net
  subscan-observer:
    environment:
      <<: *app_base
    image: subscan/api
    command: ["python","run.py","substrate"]
    networks:
      - app_net
networks:
  app_net:
    external: true
```
